### PR TITLE
Add Tutorial for creating a CRUD application using Appwrite and ReactJS

### PR DESCRIPTION
**Pull request by Niweera**
This PR  is regarding the issue [#546](https://github.com/appwrite/appwrite/issues/546).

Work done,

- Example-CRUD application
- Tutorial on Example-CRUD application
- Update main README.md file (Add details about Example-CRUD application)

### CODE REVIEW

**Review by lohanidamodar — COMMENTED** [review]
@Niweera You have done a great job with the example, tutorial and the PR. Love the effort you have put in.
1. I believe the part to add Rules (fields) to collection is missing, I had to search through the code to figure out the field names used to create rules for collection
2. And may be some information about permission should also be mentioned along with adding rules, as without permission we will not be able to perform the CRUD operation, by default the permission is null and we are not allowed to perform CRUD operations

cc @eldadfux

**Comment by Niweera** [comment]
@lohanidamodar sure I will update the tutorial.

**Comment by Niweera** [comment]
@lohanidamodar I have added a section for adding rules and permissions. Can you please check.

cc @eldadfux

**Review by lohanidamodar — APPROVED** [review]
@Niweera 
Now this is much better. Great Job!
cc @eldadfux I am very happy with the work that has been done :) really awesome job by @Niweera

**Comment by Niweera** [comment]
@lohanidamodar thank you so much, it means a lot.

**Comment by eldadfux** [comment]
All changes merged! Thank you both @Niweera & @lohanidamodar!

**Pull request merged**
