### PR TITLE
Fixed a broken link in README.md file

### PR DESCRIPTION
**Pull request by Niweera**
The broken link in the last line of the README.md file (the link to the repository) is fixed.

### CODE REVIEW

**Comment by eldadfux** [comment]
Thanks!

**Comment by Niweera** [comment]
Hey @eldadfux I would like to contribute to demos-for-react. Is there any formal procedure to this?

**Comment by eldadfux** [comment]
Take a look here: https://github.com/appwrite/appwrite/issues/546

You can also reach out on our Discord #maintainers channel if you have any question: https://appwrite.io/discord

**Comment by Niweera** [comment]
Sure, thanks.

**Pull request merged**
